### ISSUE TITLE
Suggestion) br 태그 사용의 건에 대하여

### ISSUE THREAD

**Issue by ulgoon** [Yupmac/TIL#1]
https://github.com/Yupmac/TIL/blob/099a90cb1efea21a80d636845cbe8c12d7b88be2/git/220629-git-commands.md?plain=1#L14

br 태그를 스타일링의 이유로 사용하는 것은 웹 표준에 빗겨가는 것 입니다.
마크다운에서 해당 작업이 필요하다면 `---` 나 적절한 소제목 사용 `##` 을 통해 구분하는 것이 좋습니다.
근데 엔터 두번 치면 문단 구분 될텐데 혹시 어떤 이유가 있어서 사용하신 건가요? ㅎㅎ

**Comment by Yupmac** [comment]
오 오늘 낮 시간에 어제 배웠던 부분을 복습하면서 보니 업로드했던 내용 중에 띄어쓰기가 안되어 있었습니다. 그래서 연습도 할겸 내용
수정하는데 1차적으로 제가 알고 있는 지식 선에서 해보려고 했던겁니다.  '<br> 을 활용해도 될까?' 하는 생각으로 실제
적용되는지도 궁금해서 수정본을 업로드 해본 거고요. 2차적으로는 구글링을 통해 올바른 방법을 확인했고 재수정한 것을 업로드 해야겠다고
한 것이 업로드를 하지 않았던거 같습니다. ㅜㅜ

피드백 정말 감사합니다. 수정해서 재업로드 해보겠습니다!

2022년 6월 30일 (목) 오후 6:38, Clifford Choi ***@***.***>님이 작성:

**Comment by ulgoon** [comment]
아하 그러시군요 ㅎㅎ
항상 화이팅입니다:)
